name: Sample Application

on: push

jobs:
  build:
    name: Build React App
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Install Packages 
      run: yarn install
    - name: Build 
      run: yarn react-build